### ISSUE TITLE
Plugin not loading 

### ISSUE THREAD

**Issue by powerllama** [magnoborgo/ComfyUINuke#3]
Hey Magno, not sure what's going on with my setup here. On Nuke 15.0v4, added `ComfyUINuke` to my plugin path, but nothing is being added into Nuke for some reason. If I try to manually import the toolset, this is the error I get

```
Traceback (most recent call last):
  File "<string>", line 7, in <module>
  File "/Users/powerllama/.nuke/ComfyUINuke/bvfx_comfyuinuke.py", line 150, in main
    translator = __import__(wflow_knob)
  File "/Applications/Nuke15.0v4/Nuke15.0v4.app/Contents/Resources/pythonextensions/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'basic_workflow'
```

Not sure what other troubleshooting steps I think I should do. The `init.py` is supposedly adding Workflows to the pluginPath

**Comment by magnoborgo** [comment]
the Worflows folder is addded automaticaly by the node if the nuke.pluginAddPath was added correctly.
try 
`import bvfx_comfyuinuke`
on script editor to check if the  nuke.pluginAddPath is really working.
otherwise maybe you missing/edited something on the Workflows folder?

**Comment by powerllama** [comment]
I can import `bfx_comfyuinuke` just fine, but after that the Workflow folder does not get added to path.

If I add the pluginAddPath to the plugin's menu.py, workflows folder does get added to path. Not sure why it's not loading with init.py

**Comment by magnoborgo** [comment]
adding to menu.py solves your problem? I'll add it here and update the repo if positive.

**Comment by powerllama** [comment]
It solved that specific problem. Still can't get the ToolSet to show up for some reason. Tried adding the toolset folder to the plugin path and it's not showing up. Can drag it in just fine, and after that it sees all of the workflows in the workflow folder.

**Comment by powerllama** [comment]
Ah I think I solved my issue. Should have followed the steps in the readme!

I originally added it the pluginaddpath to my menu.py, NOT my init.py. After commenting it out from menu and adding it to init, everything loads.

I'm getting some write node errors but I believe that's because i'm using a different version of nuke with those new write nodes with display and view split out.

**Comment by magnoborgo** [comment]
Glad you worked out. Yeah its needed on the init.py indeed.
