### ISSUE TITLE
name 'bvfx_comfyuinuke' is not defined error

### ISSUE THREAD

**Issue by priya-ml-halohues** [magnoborgo/ComfyUINuke#4]
Im trying to integrating comfyui_nuke into Nuke 13.0v2. I have added ComfyUINuke to my plugin path and updated the init file with the following line: nuke.pluginAddPath("/Users/render.user/.nuke/comfyUINuke"). However, when I press Tab, the comfyui tool details is not showing in the node graph and properties . when I load via comfyui_Nuke from the Toolset folder, it shows the toolset name in the node graph and properties but displays the error message: 'name 'bvfx_comfyuinuke' is not defined.' 

comfyUI_Nuke2.Write_source.ocioColorspace: no such knob
comfyUI_Nuke2.Writer_source.scene_linear: no such knob
comfyUI_Nuke2.Writer_source.display: no such knob
comfyUI_Nuke2.Writer_source.default: no such knob
comfyUI_Nuke2.Writer_source.view: no such knob
comfyUI_Nuke2.Writer_source.sRGB: no such knob
NameError: name 'bvfx_comfyuinuke' is not defined

Can you guide me on how to solve this issue? Thanks in advance.

**Comment by magnoborgo** [comment]
The issue here is that you're not adding the correct folder to the init.py (must be init.py , do not add to meny.py), maybe you're missing a last slash:
"/Users/render.user/.nuke/comfyUINuke/"

the Write error messages is just nukev13 vs nukev15 compatibility. You can re-save the toolset with Nuke13 to avoid the warnings.

**Comment by priya-ml-halohues** [comment]
updated the init file to : import nuke
nuke.pluginAddPath("/Users/render.user/.nuke/comfyUINuke/")

but again this same error
NameError: name 'bvfx_comfyuinuke' is not defined

and im suing windows os 11

**Comment by magnoborgo** [comment]
the folder path must be wrong. Here's an idea: use a Read node to navigate to the path where you installed it. 
Copy the text of the folder path from the read node, sometimes it can be something silly like "\\" instead of "/"

**Comment by priya-ml-halohues** [comment]
Thank you issue solved
