### ISSUE TITLE
Http Error 405: Method Not Allowed

### ISSUE THREAD

**Issue by tomboxmeme** [magnoborgo/ComfyUINuke#5]
Hi there,

Rather an odd question here but I've got ComfyUI and the plugin installed but for some reason I'm getting this error when I try a basic prompt.

13.53.21 Error: HTTP Error 405: Method not Allowed

Bit stuck as to what I should look for in terms of troubleshooting.

**Comment by luuude** [comment]
I am having the same problem. But my error is HTTP Error 400: Bad request.  How did you solve it?

**Comment by magnoborgo** [comment]
Please read the github project main page, all these errors are described there already.
