### ISSUE TITLE
No module named 'basic_workflow'

### ISSUE THREAD

**Issue by paboman** [magnoborgo/ComfyUINuke#7]
Error after clicking **Queue prompt**

![comfyui09](https://github.com/user-attachments/assets/aed3fa62-58e2-4750-99b7-ac51df7b8773)

![comfyui08](https://github.com/user-attachments/assets/d37b39c9-77a1-4e02-a372-db3ba0d631da)

**Comment by magnoborgo** [comment]
Your instalation is messed up, you probably edited the wrong init.py
The instalation is pretty simple, you JUST need to add a single line of code on the correct place (/.nuke/init.py)
example:
``` 
nuke.pluginAddPath("/Users/youruser/.nuke/comfyUINuke")
```

Star over with a fresh download, remove old files and copy the new ones.
and please dont flood my socials/email/etc unless its a real bug.
